### PR TITLE
Latest Steam API doesn't seem to have Init(), it has InitSafe() instead

### PR DESCRIPTION
**Pull request by corfe83**
So call the new function, and still fallback to the old if that is unavailable or fails.

Without this change, and with current steam_api64.dll, I was getting this error: `panic: Failed to find SteamAPI_Init procedure in steam_api64.dll: The specified procedure could not be found.`

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks. Could you update *.so files and *.dylib files in this repository at the same time?

**Comment by hajimehoshi** [comment]
Should we use `InitEx` for new SDKs by the way? I'm not sure `InitEx` was exposed from DLLs (and probably no).

**Comment by corfe83** [comment]
Looks like InitEx is not in the DLL. I've pushed a change to update those files as well.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Comment by hajimehoshi** [comment]
This sounds a breaking change in Steam SDK's dynamic libraries 😞

**Pull request merged**
